spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/back?serverTimezone=UTC
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 9090
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  uploda:
    path: D:\javaSpringBoot+mybatis后台管理\file\

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

